backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "project"
    label: "Project"
    folder: "src/pages/project"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "project"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Hero Image", name: "heroImage", widget: image}
      - {label: "Gallery", name: "galleryImages", widget: "list", required: false, field: {label: Image, name: image, widget: image}}

  - name: "graphic"
    label: "Graphic"
    folder: "src/pages/graphic"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "graphic"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Hero Image", name: "heroImage", widget: image}
      - {label: "Gallery", name: "galleryImages", widget: "list", required: false, field: {label: Image, name: image, widget: image}}

  - name: "illustration"
    label: "Illustration"
    folder: "src/pages/illustration"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "illustration"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Hero Image", name: "heroImage", widget: image}
      - {label: "Gallery", name: "galleryImages", widget: "list", required: false, field: {label: Image, name: image, widget: image}}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Image", name: "image", widget: image}
          - {label: "Resume", name: "resume", widget: file}
